// mockEventsData.js
// This file exports the mockEvents object for seeding the database.

// Comprehensive database of 150+ real student events
const twoDaysFromNow = new Date(Date.now() + 2 * 24 * 60 * 60 * 1000)
  .toISOString()
  .split("T")[0];

module.exports = {
  featured: [
    {
      id: 1,
      title: "HackMIT 2026",
      description:
        "The world's largest student hackathon returns with AI/ML focus. Build the future with cutting-edge technology.",
      organizer: "MIT Computer Science Society",
      location: "MIT Campus, Cambridge, MA",
      deadline: "2026-02-15",
      eventDate: "2026-03-15",
      tags: ["Hackathon", "AI/ML", "Tech", "Innovation"],
      isBookmarked: false,
      applyLink: "https://hackmit.org",
      participants: 1500,
      type: "hackathon",
    },
    {
      id: 2,
      title: "Google Summer Internship 2026",
      description:
        "Software Engineering Internship at Google. Work on products that impact billions of users worldwide.",
      organizer: "Google",
      location: "Multiple locations worldwide",
      deadline: "2026-01-31",
      eventDate: "2026-06-01",
      tags: ["Internship", "Software Engineering", "Tech"],
      isBookmarked: true,
      applyLink: "https://careers.google.com",
      participants: 50000,
      type: "internship",
    },
    {
      id: 3,
      title: "Stanford TreeHacks 2026",
      description:
        "Stanford's premier hackathon focused on solving real-world problems with technology.",
      organizer: "Stanford University",
      location: "Stanford University, CA",
      deadline: "2026-01-20",
      eventDate: "2026-02-21",
      tags: ["Hackathon", "Innovation", "Social Impact"],
      isBookmarked: false,
      applyLink: "https://treehacks.com",
      participants: 1200,
      type: "hackathon",
    },
    {
      id: 4,
      title: "Microsoft Imagine Cup 2026",
      description:
        "Global student technology competition. Build solutions that make a difference.",
      organizer: "Microsoft",
      location: "Redmond, WA",
      deadline: "2026-03-31",
      eventDate: "2026-05-15",
      tags: ["Competition", "Technology", "Innovation"],
      isBookmarked: true,
      applyLink: "https://imaginecup.microsoft.com",
      participants: 3000,
      type: "competition",
    },
    {
      id: 5,
      title: "Meta Engineering Bootcamp Fall 2025",
      description:
        "Intensive 12-week engineering program at Meta. Learn from industry experts.",
      organizer: "Meta",
      location: "Menlo Park, CA",
      deadline: "2025-09-15",
      eventDate: "2025-11-15",
      tags: ["Bootcamp", "Engineering", "Career"],
      isBookmarked: true,
      applyLink: "https://meta.com/careers",
      participants: 200,
      type: "workshop",
    },
    {
      id: 6,
      title: "Apple WWDC Student Challenge 2026",
      description:
        "Create an innovative app playground to win WWDC tickets and recognition.",
      organizer: "Apple",
      location: "Cupertino, CA",
      deadline: "2026-04-10",
      eventDate: "2026-06-10",
      tags: ["Competition", "iOS", "Development"],
      isBookmarked: false,
      applyLink: "https://developer.apple.com",
      participants: 5000,
      type: "competition",
    },
    // ... (All remaining featured events from your provided mockEvents data go here) ...
  ],
  upcoming: [
    {
      id: 6,
      title: "Apple WWDC Student Challenge 2026",
      description:
        "Create an innovative app playground to win WWDC tickets and recognition.",
      organizer: "Apple",
      location: "Cupertino, CA",
      deadline: "2026-04-10",
      eventDate: "2026-06-10",
      tags: ["Competition", "iOS", "Development"],
      isBookmarked: false,
      applyLink: "https://developer.apple.com",
      participants: 5000,
      type: "competition",
    },
    {
      id: 7,
      title: "Amazon SDE Intern 2026",
      description:
        "Software Development Engineer Internship at Amazon. Work on scalable systems.",
      organizer: "Amazon",
      location: "Seattle, WA",
      deadline: twoDaysFromNow,
      eventDate: "2026-06-01",
      tags: ["Internship", "Software Engineering", "Cloud"],
      isBookmarked: true,
      applyLink: "https://amazon.jobs",
      participants: 8000,
      type: "internship",
    },
    {
      id: 8,
      title: "Tesla Engineering Internship 2026",
      description:
        "Engineering internship at Tesla working on sustainable energy and transportation.",
      organizer: "Tesla",
      location: "Austin, TX",
      deadline: "2026-01-20",
      eventDate: "2026-05-20",
      tags: ["Internship", "Engineering", "Sustainability"],
      isBookmarked: false,
      applyLink: "https://tesla.com/careers",
      participants: 1000,
      type: "internship",
    },
    {
      id: 9,
      title: "Netflix Software Engineering Intern",
      description:
        "Work on streaming technology that entertains millions worldwide.",
      organizer: "Netflix",
      location: "Los Gatos, CA",
      deadline: "2026-02-01",
      eventDate: "2026-06-15",
      tags: ["Internship", "Streaming", "Software"],
      isBookmarked: false,
      applyLink: "https://jobs.netflix.com",
      participants: 500,
      type: "internship",
    },
    {
      id: 10,
      title: "Spotify Music Technology Internship",
      description: "Shape the future of music streaming and audio technology.",
      organizer: "Spotify",
      location: "Stockholm, Sweden",
      deadline: "2026-01-15",
      eventDate: "2026-06-01",
      tags: ["Internship", "Music", "Technology"],
      isBookmarked: false,
      applyLink: "https://spotify.com/careers",
      participants: 300,
      type: "internship",
    },

    // Major Hackathons
    {
      id: 11,
      title: "CalHacks 12.0",
      description:
        "UC Berkeley's premier hackathon. Build the next generation of technology.",
      organizer: "UC Berkeley",
      location: "UC Berkeley, CA",
      deadline: "2025-09-15",
      eventDate: "2025-10-25",
      tags: ["Hackathon", "Innovation", "Tech"],
      isBookmarked: true,
      applyLink: "https://calhacks.io",
      participants: 1800,
      type: "hackathon",
    },
    {
      id: 12,
      title: "HackDuke 2025",
      description:
        "Duke University's hackathon with tracks in health, inequality, and environment.",
      organizer: "Duke University",
      location: "Durham, NC",
      deadline: "2025-10-01",
      eventDate: "2025-11-08",
      tags: ["Hackathon", "Health Tech", "Social Impact"],
      isBookmarked: false,
      applyLink: "https://hackduke.org",
      participants: 600,
      type: "hackathon",
    },
    {
      id: 13,
      title: "MHacks 17",
      description:
        "University of Michigan's hackathon focused on innovation and creativity.",
      organizer: "University of Michigan",
      location: "Ann Arbor, MI",
      deadline: "2025-09-15",
      eventDate: "2025-10-11",
      tags: ["Hackathon", "Innovation", "Creativity"],
      isBookmarked: false,
      applyLink: "https://mhacks.org",
      participants: 1000,
      type: "hackathon",
    },
    {
      id: 14,
      title: "HackHarvard 2025",
      description:
        "Harvard University's premier hackathon focused on global impact.",
      organizer: "Harvard University",
      location: "Cambridge, MA",
      deadline: "2025-09-01",
      eventDate: "2025-10-18",
      tags: ["Hackathon", "Global Impact", "Innovation"],
      isBookmarked: false,
      applyLink: "https://hackharvard.io",
      participants: 800,
      type: "hackathon",
    },
    {
      id: 15,
      title: "PennApps XXVII",
      description:
        "University of Pennsylvania's hackathon - one of the oldest and largest.",
      organizer: "University of Pennsylvania",
      location: "Philadelphia, PA",
      deadline: "2026-08-25",
      eventDate: "2026-09-06",
      tags: ["Hackathon", "Innovation", "Technology"],
      isBookmarked: true,
      applyLink: "https://pennapps.com",
      participants: 1200,
      type: "hackathon",
    },

    // Tech Competitions
    {
      id: 16,
      title: "ACM ICPC World Finals 2026",
      description:
        "The world championship of programming contests for university students.",
      organizer: "ACM",
      location: "Manila, Philippines",
      deadline: "2026-02-01",
      eventDate: "2026-04-15",
      tags: ["Competition", "Programming", "Algorithm"],
      isBookmarked: true,
      applyLink: "https://icpc.global",
      participants: 140,
      type: "competition",
    },
    {
      id: 17,
      title: "Nvidia GTC Student Competition 2026",
      description:
        "GPU computing competition focused on AI and machine learning applications.",
      organizer: "Nvidia",
      location: "San Jose, CA",
      deadline: "2026-02-28",
      eventDate: "2026-03-20",
      tags: ["Competition", "AI", "GPU Computing"],
      isBookmarked: false,
      applyLink: "https://nvidia.com/gtc",
      participants: 800,
      type: "competition",
    },
    {
      id: 18,
      title: "Unity Student Challenge 2026",
      description:
        "Game development competition using Unity engine with expert mentorship.",
      organizer: "Unity Technologies",
      location: "Online",
      deadline: "2026-04-30",
      eventDate: "2026-06-15",
      tags: ["Competition", "Game Development", "Unity"],
      isBookmarked: true,
      applyLink: "https://unity.com/learn",
      participants: 2000,
      type: "competition",
    },
    {
      id: 19,
      title: "Citadel Datathon 2026",
      description:
        "Data science competition with real financial datasets and expert mentorship.",
      organizer: "Citadel",
      location: "Chicago, IL",
      deadline: "2026-08-15",
      eventDate: "2026-09-28",
      tags: ["Competition", "Data Science", "Finance"],
      isBookmarked: false,
      applyLink: "https://citadel.com/careers",
      participants: 300,
      type: "competition",
    },
    {
      id: 20,
      title: "TechCrunch Disrupt Startup Battlefield 2026",
      description:
        "Pitch your startup to top VCs and compete for the $100K grand prize.",
      organizer: "TechCrunch",
      location: "San Francisco, CA",
      deadline: "2026-07-01",
      eventDate: "2026-09-20",
      tags: ["Competition", "Startup", "Pitch"],
      isBookmarked: false,
      applyLink: "https://techcrunch.com/events",
      participants: 200,
      type: "competition",
    },

    // Indian College Festivals
    {
      id: 21,
      title: "Mood Indigo 2025 - IIT Bombay",
      description:
        "Asia's largest college cultural festival featuring music, dance, drama, and comedy performances.",
      organizer: "IIT Bombay",
      location: "Mumbai, Maharashtra",
      deadline: "2025-11-15",
      eventDate: "2025-12-27",
      tags: ["Cultural Festival", "Music", "Dance", "Arts"],
      isBookmarked: false,
      applyLink: "https://moodi.org",
      participants: 150000,
      type: "seminar",
    },
    {
      id: 22,
      title: "Shaastra 2026 - IIT Madras",
      description:
        "South India's largest technical festival with competitions, workshops, and tech talks.",
      organizer: "IIT Madras",
      location: "Chennai, Tamil Nadu",
      deadline: "2025-12-20",
      eventDate: "2026-01-02",
      tags: ["Tech Festival", "Competition", "Workshop", "Innovation"],
      isBookmarked: true,
      applyLink: "https://shaastra.org",
      participants: 50000,
      type: "competition",
    },
    {
      id: 23,
      title: "Techfest 2026 - IIT Bombay",
      description:
        "India's largest science and technology festival with robotics, coding competitions.",
      organizer: "IIT Bombay",
      location: "Mumbai, Maharashtra",
      deadline: "2025-12-01",
      eventDate: "2026-01-15",
      tags: ["Tech Festival", "Robotics", "Coding", "Science"],
      isBookmarked: false,
      applyLink: "https://techfest.org",
      participants: 70000,
      type: "competition",
    },
    {
      id: 24,
      title: "Saarang 2026 - IIT Madras",
      description:
        "One of India's premier cultural festivals featuring celebrities and cultural competitions.",
      organizer: "IIT Madras",
      location: "Chennai, Tamil Nadu",
      deadline: "2025-12-30",
      eventDate: "2026-02-05",
      tags: ["Cultural Festival", "Celebrity Shows", "Music", "Arts"],
      isBookmarked: false,
      applyLink: "https://saarang.org",
      participants: 80000,
      type: "seminar",
    },
    {
      id: 25,
      title: "Alcheringa 2026 - IIT Guwahati",
      description:
        "North East India's biggest cultural festival celebrating diversity and talent.",
      organizer: "IIT Guwahati",
      location: "Guwahati, Assam",
      deadline: "2025-12-15",
      eventDate: "2026-02-12",
      tags: ["Cultural Festival", "Music", "Dance", "Drama"],
      isBookmarked: true,
      applyLink: "https://alcheringa.in",
      participants: 40000,
      type: "seminar",
    },

    // More International Hackathons
    {
      id: 26,
      title: "Hack the North 2026",
      description: "Canada's biggest hackathon at University of Waterloo.",
      organizer: "University of Waterloo",
      location: "Waterloo, Canada",
      deadline: "2026-07-15",
      eventDate: "2026-09-19",
      tags: ["Hackathon", "Innovation", "Global"],
      isBookmarked: false,
      applyLink: "https://hackthenorth.com",
      participants: 1000,
      type: "hackathon",
    },
    {
      id: 27,
      title: "DubHacks 2025",
      description:
        "University of Washington's premier hackathon focused on social good.",
      organizer: "University of Washington",
      location: "Seattle, WA",
      deadline: "2025-09-20",
      eventDate: "2025-10-12",
      tags: ["Hackathon", "Social Good", "Innovation"],
      isBookmarked: false,
      applyLink: "https://dubhacks.co",
      participants: 800,
      type: "hackathon",
    },
    {
      id: 28,
      title: "LA Hacks 2026",
      description:
        "UCLA's hackathon bringing together students from across the west coast.",
      organizer: "UCLA",
      location: "Los Angeles, CA",
      deadline: "2026-03-15",
      eventDate: "2026-04-05",
      tags: ["Hackathon", "West Coast", "Innovation"],
      isBookmarked: false,
      applyLink: "https://lahacks.com",
      participants: 1500,
      type: "hackathon",
    },
    {
      id: 29,
      title: "VandyHacks IX",
      description:
        "Vanderbilt University's hackathon with focus on social innovation.",
      organizer: "Vanderbilt University",
      location: "Nashville, TN",
      deadline: "2025-09-10",
      eventDate: "2025-10-04",
      tags: ["Hackathon", "Social Innovation", "Technology"],
      isBookmarked: false,
      applyLink: "https://vandyhacks.org",
      participants: 400,
      type: "hackathon",
    },
    {
      id: 30,
      title: "BrickHack 11",
      description:
        "Rochester Institute of Technology's weekend-long hackathon.",
      organizer: "Rochester Institute of Technology",
      location: "Rochester, NY",
      deadline: "2026-02-15",
      eventDate: "2026-03-08",
      tags: ["Hackathon", "Innovation", "Technology"],
      isBookmarked: false,
      applyLink: "https://brickhack.io",
      participants: 400,
      type: "hackathon",
    },

    // More Tech Internships
    {
      id: 31,
      title: "Jane Street Trading Internship 2026",
      description:
        "Quantitative trading internship at one of the top trading firms.",
      organizer: "Jane Street",
      location: "New York, NY",
      deadline: "2026-01-10",
      eventDate: "2026-06-01",
      tags: ["Internship", "Trading", "Quantitative"],
      isBookmarked: true,
      applyLink: "https://janestreet.com/careers",
      participants: 100,
      type: "internship",
    },
    {
      id: 32,
      title: "Palantir Path Internship 2026",
      description:
        "Forward Deployed Software Engineer internship working with real clients.",
      organizer: "Palantir Technologies",
      location: "Palo Alto, CA",
      deadline: "2026-02-01",
      eventDate: "2026-06-15",
      tags: ["Internship", "Software Engineering", "Data"],
      isBookmarked: false,
      applyLink: "https://palantir.com/careers",
      participants: 500,
      type: "internship",
    },
    {
      id: 33,
      title: "Uber Engineering Apprenticeship 2026",
      description:
        "12-month software engineering apprenticeship program at Uber.",
      organizer: "Uber",
      location: "San Francisco, CA",
      deadline: "2026-03-15",
      eventDate: "2026-07-01",
      tags: ["Apprenticeship", "Software Engineering", "Transportation"],
      isBookmarked: false,
      applyLink: "https://uber.com/careers",
      participants: 50,
      type: "internship",
    },
    {
      id: 34,
      title: "DoorDash Engineering Apprenticeship 2026",
      description:
        "Software engineering apprenticeship in logistics and marketplace technology.",
      organizer: "DoorDash",
      location: "San Francisco, CA",
      deadline: "2026-03-01",
      eventDate: "2026-06-15",
      tags: ["Apprenticeship", "Logistics", "Engineering"],
      isBookmarked: false,
      applyLink: "https://doordash.com/careers",
      participants: 30,
      type: "internship",
    },
    {
      id: 35,
      title: "Riot Games Internship Program 2026",
      description:
        "Game development internship working on League of Legends and Valorant.",
      organizer: "Riot Games",
      location: "Los Angeles, CA",
      deadline: "2026-02-15",
      eventDate: "2026-06-01",
      tags: ["Internship", "Game Development", "Engineering"],
      isBookmarked: false,
      applyLink: "https://riotgames.com/careers",
      participants: 200,
      type: "internship",
    },

    // Workshops and Training Programs
    {
      id: 36,
      title: "YC Startup School Winter 2026",
      description:
        "10-week online course for founders. Learn how to build and scale a startup.",
      organizer: "Y Combinator",
      location: "Online",
      deadline: "2025-12-15",
      eventDate: "2026-01-15",
      tags: ["Startup", "Entrepreneurship", "Business"],
      isBookmarked: false,
      applyLink: "https://startupschool.org",
      participants: 10000,
      type: "workshop",
    },
    {
      id: 37,
      title: "MongoDB University Fall Program 2025",
      description:
        "Comprehensive database development program with certification.",
      organizer: "MongoDB",
      location: "Online",
      deadline: "2025-10-01",
      eventDate: "2025-11-15",
      tags: ["Workshop", "Database", "Development"],
      isBookmarked: false,
      applyLink: "https://university.mongodb.com",
      participants: 2000,
      type: "workshop",
    },
    {
      id: 38,
      title: "Docker Student Developer Program Winter 2026",
      description:
        "Learn containerization and DevOps practices with hands-on workshops.",
      organizer: "Docker",
      location: "Online",
      deadline: "2025-12-15",
      eventDate: "2026-01-20",
      tags: ["Workshop", "DevOps", "Containers"],
      isBookmarked: false,
      applyLink: "https://docker.com/community",
      participants: 1000,
      type: "workshop",
    },
    {
      id: 39,
      title: "GitHub Field Day Fall 2025",
      description:
        "Open source contribution workshop and networking event for students.",
      organizer: "GitHub",
      location: "San Francisco, CA",
      deadline: "2025-10-15",
      eventDate: "2025-11-20",
      tags: ["Workshop", "Open Source", "Collaboration"],
      isBookmarked: false,
      applyLink: "https://github.com/events",
      participants: 400,
      type: "workshop",
    },
    {
      id: 40,
      title: "Salesforce Trailhead Academy Winter 2026",
      description:
        "CRM and cloud computing certification program for students.",
      organizer: "Salesforce",
      location: "San Francisco, CA",
      deadline: "2025-12-15",
      eventDate: "2026-02-01",
      tags: ["Workshop", "CRM", "Cloud Computing"],
      isBookmarked: false,
      applyLink: "https://trailhead.salesforce.com",
      participants: 500,
      type: "workshop",
    },

    // Conferences and Seminars
    {
      id: 41,
      title: "Shopify Unite Developer Conference 2026",
      description:
        "Learn about the latest in e-commerce technology and platform development.",
      organizer: "Shopify",
      location: "Toronto, Canada",
      deadline: "2026-04-01",
      eventDate: "2026-05-10",
      tags: ["Conference", "E-commerce", "Development"],
      isBookmarked: false,
      applyLink: "https://unite.shopify.com",
      participants: 2000,
      type: "seminar",
    },
    {
      id: 42,
      title: "Figma Config Student Track 2026",
      description:
        "Design conference with dedicated student sessions and portfolio reviews.",
      organizer: "Figma",
      location: "San Francisco, CA",
      deadline: "2026-05-01",
      eventDate: "2026-06-26",
      tags: ["Conference", "Design", "UI/UX"],
      isBookmarked: false,
      applyLink: "https://config.figma.com",
      participants: 1500,
      type: "seminar",
    },
    {
      id: 43,
      title: "Databricks Academic Alliance Summit 2026",
      description:
        "Learn about big data, machine learning, and data engineering.",
      organizer: "Databricks",
      location: "San Francisco, CA",
      deadline: "2026-06-01",
      eventDate: "2026-07-15",
      tags: ["Conference", "Data Science", "ML"],
      isBookmarked: false,
      applyLink: "https://databricks.com/learn",
      participants: 1000,
      type: "seminar",
    },
    {
      id: 44,
      title: "Twilio SIGNAL Developer Conference 2026",
      description:
        "Communications and customer engagement platform conference for developers.",
      organizer: "Twilio",
      location: "San Francisco, CA",
      deadline: "2026-07-01",
      eventDate: "2026-08-14",
      tags: ["Conference", "Communications", "API"],
      isBookmarked: false,
      applyLink: "https://signal.twilio.com",
      participants: 3000,
      type: "seminar",
    },
    {
      id: 45,
      title: "Roblox Developer Conference 2026",
      description:
        "Game development conference focused on the Roblox platform and metaverse.",
      organizer: "Roblox",
      location: "San Mateo, CA",
      deadline: "2026-08-01",
      eventDate: "2026-09-11",
      tags: ["Conference", "Game Development", "Metaverse"],
      isBookmarked: false,
      applyLink: "https://roblox.com/develop",
      participants: 2000,
      type: "seminar",
    },

    // More Global Events - 46-75
    {
      id: 46,
      title: "HackZurich 2026 - Switzerland",
      description:
        "Europe's largest hackathon bringing together international students.",
      organizer: "ETH Zurich",
      location: "Zurich, Switzerland",
      deadline: "2026-08-15",
      eventDate: "2026-09-20",
      tags: ["Hackathon", "Europe", "International"],
      isBookmarked: false,
      applyLink: "https://hackzurich.com",
      participants: 600,
      type: "hackathon",
    },
    {
      id: 47,
      title: "HackTech 2026 - Caltech",
      description: "California Institute of Technology's premier hackathon.",
      organizer: "Caltech",
      location: "Pasadena, CA",
      deadline: "2026-02-10",
      eventDate: "2026-03-05",
      tags: ["Hackathon", "Science", "Technology"],
      isBookmarked: false,
      applyLink: "https://hacktech.caltech.edu",
      participants: 400,
      type: "hackathon",
    },
    {
      id: 48,
      title: "NASA Space Apps Challenge 2025",
      description:
        "Global hackathon to solve challenges related to space exploration and Earth science.",
      organizer: "NASA",
      location: "Global - Multiple locations",
      deadline: "2025-09-15",
      eventDate: "2025-10-05",
      tags: ["Hackathon", "Space", "Science"],
      isBookmarked: false,
      applyLink: "https://spaceappschallenge.org",
      participants: 25000,
      type: "hackathon",
    },
    {
      id: 49,
      title: "Boiler Make XII",
      description:
        "Purdue University's largest hackathon bringing together innovative minds.",
      organizer: "Purdue University",
      location: "West Lafayette, IN",
      deadline: "2025-12-10",
      eventDate: "2026-01-24",
      tags: ["Hackathon", "Innovation", "Engineering"],
      isBookmarked: true,
      applyLink: "https://boilermake.org",
      participants: 500,
      type: "hackathon",
    },
    {
      id: 50,
      title: "YHack 2025",
      description:
        "Yale University's premier hackathon focused on social entrepreneurship.",
      organizer: "Yale University",
      location: "New Haven, CT",
      deadline: "2025-10-15",
      eventDate: "2025-11-22",
      tags: ["Hackathon", "Social Entrepreneurship", "Innovation"],
      isBookmarked: false,
      applyLink: "https://yhack.org",
      participants: 700,
      type: "hackathon",
    },

    // Fintech and Finance Events - 51-65
    {
      id: 51,
      title: "Two Sigma Diversity in Tech Summit 2026",
      description:
        "Conference promoting diversity and inclusion in technology careers.",
      organizer: "Two Sigma",
      location: "New York, NY",
      deadline: "2026-06-01",
      eventDate: "2026-07-18",
      tags: ["Conference", "Diversity", "Career"],
      isBookmarked: false,
      applyLink: "https://twosigma.com/careers",
      participants: 500,
      type: "seminar",
    },
    {
      id: 52,
      title: "Capital One Software Engineering Summit 2026",
      description: "Learn about fintech and software engineering in banking.",
      organizer: "Capital One",
      location: "McLean, VA",
      deadline: "2026-04-01",
      eventDate: "2026-05-15",
      tags: ["Conference", "Fintech", "Software Engineering"],
      isBookmarked: false,
      applyLink: "https://capitalone.com/careers",
      participants: 300,
      type: "seminar",
    },
    {
      id: 53,
      title: "Coinbase Crypto Career Workshop 2026",
      description:
        "Learn about cryptocurrency, blockchain, and fintech career opportunities.",
      organizer: "Coinbase",
      location: "San Francisco, CA",
      deadline: "2026-06-01",
      eventDate: "2026-07-10",
      tags: ["Workshop", "Cryptocurrency", "Blockchain"],
      isBookmarked: false,
      applyLink: "https://coinbase.com/careers",
      participants: 200,
      type: "workshop",
    },
    {
      id: 54,
      title: "Stripe Atlas Startup Workshop Winter 2026",
      description:
        "Learn how to incorporate and scale your startup with Stripe Atlas.",
      organizer: "Stripe",
      location: "Online",
      deadline: "2026-01-10",
      eventDate: "2026-02-15",
      tags: ["Workshop", "Startup", "Fintech"],
      isBookmarked: false,
      applyLink: "https://stripe.com/atlas",
      participants: 500,
      type: "workshop",
    },
    {
      id: 55,
      title: "BlackRock Technology Summit 2026",
      description:
        "Explore technology in financial services and investment management.",
      organizer: "BlackRock",
      location: "New York, NY",
      deadline: "2026-03-15",
      eventDate: "2026-04-20",
      tags: ["Conference", "Finance", "Technology"],
      isBookmarked: false,
      applyLink: "https://blackrock.com/careers",
      participants: 400,
      type: "seminar",
    },

    // AI and Machine Learning Events - 56-70
    {
      id: 56,
      title: "OpenAI DevDay 2026",
      description:
        "Developer conference showcasing latest AI tools and technologies.",
      organizer: "OpenAI",
      location: "San Francisco, CA",
      deadline: "2026-09-15",
      eventDate: "2026-11-01",
      tags: ["Conference", "AI", "Development"],
      isBookmarked: true,
      applyLink: "https://openai.com/devday",
      participants: 1000,
      type: "seminar",
    },
    {
      id: 57,
      title: "Anthropic AI Safety Workshop 2026",
      description:
        "Workshop on AI safety research and responsible AI development.",
      organizer: "Anthropic",
      location: "San Francisco, CA",
      deadline: "2026-05-01",
      eventDate: "2026-06-15",
      tags: ["Workshop", "AI Safety", "Research"],
      isBookmarked: false,
      applyLink: "https://anthropic.com",
      participants: 200,
      type: "workshop",
    },
    {
      id: 58,
      title: "ICLR 2026 Student Track",
      description:
        "International Conference on Learning Representations student program.",
      organizer: "ICLR Foundation",
      location: "Vienna, Austria",
      deadline: "2026-01-15",
      eventDate: "2026-05-24",
      tags: ["Conference", "Machine Learning", "Research"],
      isBookmarked: false,
      applyLink: "https://iclr.cc",
      participants: 300,
      type: "seminar",
    },
    {
      id: 59,
      title: "NeurIPS 2026 Student Symposium",
      description:
        "Neural Information Processing Systems conference for students.",
      organizer: "NeurIPS Foundation",
      location: "New Orleans, LA",
      deadline: "2026-07-01",
      eventDate: "2026-12-06",
      tags: ["Conference", "AI", "Neural Networks"],
      isBookmarked: false,
      applyLink: "https://neurips.cc",
      participants: 500,
      type: "seminar",
    },
    {
      id: 60,
      title: "Coursera for Campus AI Workshop Fall 2025",
      description:
        "Machine learning and AI curriculum workshop for computer science students.",
      organizer: "Coursera",
      location: "Mountain View, CA",
      deadline: "2025-09-01",
      eventDate: "2025-10-10",
      tags: ["Workshop", "AI", "Machine Learning"],
      isBookmarked: false,
      applyLink: "https://coursera.org/campus",
      participants: 200,
      type: "workshop",
    },

    // Gaming and Entertainment - 61-75
    {
      id: 61,
      title: "Epic Games Unreal Engine Student Challenge",
      description: "Game development competition using Unreal Engine 5.",
      organizer: "Epic Games",
      location: "Online",
      deadline: "2026-03-31",
      eventDate: "2026-05-15",
      tags: ["Competition", "Game Development", "Unreal"],
      isBookmarked: false,
      applyLink: "https://unrealengine.com/students",
      participants: 1500,
      type: "competition",
    },
    {
      id: 62,
      title: "Discord Community Building Workshop",
      description: "Learn to build and manage online communities.",
      organizer: "Discord",
      location: "San Francisco, CA",
      deadline: "2026-04-15",
      eventDate: "2026-06-01",
      tags: ["Workshop", "Community", "Social"],
      isBookmarked: false,
      applyLink: "https://discord.com/developers",
      participants: 300,
      type: "workshop",
    },
    {
      id: 63,
      title: "Twitch Creator Camp 2026",
      description: "Content creation and streaming workshop for students.",
      organizer: "Twitch",
      location: "Austin, TX",
      deadline: "2026-05-01",
      eventDate: "2026-07-15",
      tags: ["Workshop", "Streaming", "Content"],
      isBookmarked: false,
      applyLink: "https://twitch.tv/creatorcamp",
      participants: 200,
      type: "workshop",
    },
    {
      id: 64,
      title: "Valve Steam Deck Developer Workshop",
      description: "Game development workshop for Steam Deck platform.",
      organizer: "Valve Corporation",
      location: "Seattle, WA",
      deadline: "2026-06-15",
      eventDate: "2026-08-10",
      tags: ["Workshop", "Gaming", "Hardware"],
      isBookmarked: false,
      applyLink: "https://steamdeck.com/developers",
      participants: 150,
      type: "workshop",
    },
    {
      id: 65,
      title: "Unity Global Student Challenge 2026",
      description: "Worldwide game development competition with Unity.",
      organizer: "Unity Technologies",
      location: "Global - Online",
      deadline: "2026-06-30",
      eventDate: "2026-09-01",
      tags: ["Competition", "Global", "Unity"],
      isBookmarked: true,
      applyLink: "https://unity.com/students",
      participants: 5000,
      type: "competition",
    },

    // Cloud and DevOps - 76-90
    {
      id: 66,
      title: "AWS re:Invent Student Track 2026",
      description:
        "Amazon Web Services conference with dedicated student sessions.",
      organizer: "Amazon Web Services",
      location: "Las Vegas, NV",
      deadline: "2026-10-01",
      eventDate: "2026-11-28",
      tags: ["Conference", "Cloud", "AWS"],
      isBookmarked: false,
      applyLink: "https://reinvent.awsevents.com",
      participants: 2000,
      type: "seminar",
    },
    {
      id: 67,
      title: "Microsoft Build Student Zone 2026",
      description:
        "Microsoft's developer conference with student-focused content.",
      organizer: "Microsoft",
      location: "Seattle, WA",
      deadline: "2026-04-01",
      eventDate: "2026-05-21",
      tags: ["Conference", "Microsoft", "Development"],
      isBookmarked: false,
      applyLink: "https://mybuild.microsoft.com",
      participants: 1500,
      type: "seminar",
    },
    {
      id: 68,
      title: "Google Cloud Next Student Program 2026",
      description: "Google Cloud's premier conference with student workshops.",
      organizer: "Google Cloud",
      location: "San Francisco, CA",
      deadline: "2026-03-15",
      eventDate: "2026-04-10",
      tags: ["Conference", "Google Cloud", "Cloud"],
      isBookmarked: false,
      applyLink: "https://cloud.withgoogle.com/next",
      participants: 1000,
      type: "seminar",
    },
    {
      id: 69,
      title: "Kubernetes Community Days Student Track",
      description: "Container orchestration workshop and community event.",
      organizer: "Cloud Native Computing Foundation",
      location: "Multiple Cities",
      deadline: "2026-05-15",
      eventDate: "2026-07-20",
      tags: ["Workshop", "Kubernetes", "DevOps"],
      isBookmarked: false,
      applyLink: "https://kubernetescommunitydays.org",
      participants: 800,
      type: "workshop",
    },
    {
      id: 70,
      title: "HashiCorp User Group Student Meetup",
      description: "Infrastructure automation and cloud workshops.",
      organizer: "HashiCorp",
      location: "San Francisco, CA",
      deadline: "2026-06-01",
      eventDate: "2026-08-15",
      tags: ["Workshop", "Infrastructure", "DevOps"],
      isBookmarked: false,
      applyLink: "https://hashicorp.com/community",
      participants: 300,
      type: "workshop",
    },

    // Cybersecurity Events - 71-85
    {
      id: 71,
      title: "DEF CON Student Village 2026",
      description:
        "World's largest hacking conference with dedicated student area.",
      organizer: "DEF CON",
      location: "Las Vegas, NV",
      deadline: "2026-07-01",
      eventDate: "2026-08-08",
      tags: ["Conference", "Cybersecurity", "Hacking"],
      isBookmarked: false,
      applyLink: "https://defcon.org",
      participants: 1000,
      type: "seminar",
    },
    {
      id: 72,
      title: "Black Hat Student Scholarship Program",
      description:
        "Premier cybersecurity conference with student scholarships.",
      organizer: "Black Hat",
      location: "Las Vegas, NV",
      deadline: "2026-05-15",
      eventDate: "2026-08-03",
      tags: ["Conference", "Security", "Scholarship"],
      isBookmarked: false,
      applyLink: "https://blackhat.com",
      participants: 500,
      type: "seminar",
    },
    {
      id: 73,
      title: "CyberSeek Student CTF Championship",
      description: "Capture The Flag cybersecurity competition for students.",
      organizer: "NIST",
      location: "Online",
      deadline: "2026-04-30",
      eventDate: "2026-06-15",
      tags: ["Competition", "CTF", "Cybersecurity"],
      isBookmarked: false,
      applyLink: "https://cyberseek.org",
      participants: 2000,
      type: "competition",
    },
    {
      id: 74,
      title: "SANS Student Summit 2026",
      description:
        "Cybersecurity training and career development for students.",
      organizer: "SANS Institute",
      location: "Washington, DC",
      deadline: "2026-02-15",
      eventDate: "2026-04-05",
      tags: ["Conference", "Training", "Security"],
      isBookmarked: false,
      applyLink: "https://sans.org/student-summit",
      participants: 300,
      type: "seminar",
    },
    {
      id: 75,
      title: "OWASP Student Chapter Summit",
      description: "Web application security workshop and networking.",
      organizer: "OWASP Foundation",
      location: "Austin, TX",
      deadline: "2026-08-01",
      eventDate: "2026-09-20",
      tags: ["Workshop", "Web Security", "OWASP"],
      isBookmarked: false,
      applyLink: "https://owasp.org/students",
      participants: 400,
      type: "workshop",
    },

    // Data Science and Analytics - 76-90
    {
      id: 76,
      title: "Tableau Student Data Day 2026",
      description: "Data visualization and analytics workshop for students.",
      organizer: "Tableau",
      location: "Seattle, WA",
      deadline: "2026-03-01",
      eventDate: "2026-04-15",
      tags: ["Workshop", "Data Visualization", "Analytics"],
      isBookmarked: false,
      applyLink: "https://tableau.com/academic",
      participants: 500,
      type: "workshop",
    },
    {
      id: 77,
      title: "Snowflake Data Cloud Summit Student Track",
      description: "Cloud data platform conference with student sessions.",
      organizer: "Snowflake",
      location: "San Francisco, CA",
      deadline: "2026-05-01",
      eventDate: "2026-06-15",
      tags: ["Conference", "Data Cloud", "Analytics"],
      isBookmarked: false,
      applyLink: "https://snowflake.com/summit",
      participants: 300,
      type: "seminar",
    },
    {
      id: 78,
      title: "Kaggle Student Competition Series 2026",
      description: "Data science competition platform for student teams.",
      organizer: "Kaggle",
      location: "Online",
      deadline: "2026-07-15",
      eventDate: "2026-09-01",
      tags: ["Competition", "Data Science", "Machine Learning"],
      isBookmarked: true,
      applyLink: "https://kaggle.com/competitions",
      participants: 10000,
      type: "competition",
    },
    {
      id: 79,
      title: "Databricks Lakehouse Student Workshop",
      description: "Modern data architecture workshop with hands-on labs.",
      organizer: "Databricks",
      location: "San Francisco, CA",
      deadline: "2026-04-15",
      eventDate: "2026-06-01",
      tags: ["Workshop", "Data Engineering", "Lakehouse"],
      isBookmarked: false,
      applyLink: "https://databricks.com/learn",
      participants: 200,
      type: "workshop",
    },
    {
      id: 80,
      title: "Apache Spark Student Meetup 2026",
      description: "Big data processing framework workshop and networking.",
      organizer: "Apache Software Foundation",
      location: "San Jose, CA",
      deadline: "2026-06-01",
      eventDate: "2026-08-10",
      tags: ["Workshop", "Big Data", "Spark"],
      isBookmarked: false,
      applyLink: "https://spark.apache.org/community",
      participants: 400,
      type: "workshop",
    },

    // Mobile Development - 81-95
    {
      id: 81,
      title: "Flutter Forward Student Conference 2026",
      description: "Google's Flutter framework conference with student tracks.",
      organizer: "Google",
      location: "Mountain View, CA",
      deadline: "2026-01-15",
      eventDate: "2026-03-01",
      tags: ["Conference", "Flutter", "Mobile"],
      isBookmarked: false,
      applyLink: "https://flutter.dev/events",
      participants: 800,
      type: "seminar",
    },
    {
      id: 82,
      title: "React Native Student Bootcamp",
      description: "Cross-platform mobile development intensive workshop.",
      organizer: "Meta",
      location: "New York, NY",
      deadline: "2026-02-01",
      eventDate: "2026-04-10",
      tags: ["Workshop", "React Native", "Mobile"],
      isBookmarked: false,
      applyLink: "https://reactnative.dev/community",
      participants: 300,
      type: "workshop",
    },
    {
      id: 83,
      title: "Swift Student Challenge 2026",
      description: "Apple's annual coding challenge for Swift developers.",
      organizer: "Apple",
      location: "Online",
      deadline: "2026-02-25",
      eventDate: "2026-06-10",
      tags: ["Competition", "Swift", "iOS"],
      isBookmarked: true,
      applyLink: "https://developer.apple.com/swift-student-challenge",
      participants: 5000,
      type: "competition",
    },
    {
      id: 84,
      title: "Android Dev Summit Student Track 2026",
      description: "Google's Android development conference for students.",
      organizer: "Google",
      location: "Mountain View, CA",
      deadline: "2026-09-15",
      eventDate: "2026-10-27",
      tags: ["Conference", "Android", "Mobile"],
      isBookmarked: false,
      applyLink: "https://developer.android.com/events",
      participants: 600,
      type: "seminar",
    },
    {
      id: 85,
      title: "Ionic Student Developer Meetup",
      description: "Hybrid mobile app development workshop.",
      organizer: "Ionic",
      location: "Austin, TX",
      deadline: "2026-05-15",
      eventDate: "2026-07-20",
      tags: ["Workshop", "Ionic", "Hybrid Apps"],
      isBookmarked: false,
      applyLink: "https://ionic.io/community",
      participants: 200,
      type: "workshop",
    },

    // Web Development - 86-100
    {
      id: 86,
      title: "Vercel Next.js Conference Student Track 2026",
      description: "Modern web development conference with Next.js focus.",
      organizer: "Vercel",
      location: "San Francisco, CA",
      deadline: "2026-09-01",
      eventDate: "2026-10-25",
      tags: ["Conference", "Next.js", "Web Development"],
      isBookmarked: false,
      applyLink: "https://nextjs.org/conf",
      participants: 1000,
      type: "seminar",
    },
    {
      id: 87,
      title: "Netlify Jamstack Student Workshop",
      description: "Modern web architecture workshop with JAMstack.",
      organizer: "Netlify",
      location: "San Francisco, CA",
      deadline: "2026-04-01",
      eventDate: "2026-05-15",
      tags: ["Workshop", "JAMstack", "Web"],
      isBookmarked: false,
      applyLink: "https://netlify.com/community",
      participants: 400,
      type: "workshop",
    },
    {
      id: 88,
      title: "Svelte Society Student Meetup 2026",
      description: "Svelte framework workshop and community event.",
      organizer: "Svelte Society",
      location: "Online",
      deadline: "2026-06-15",
      eventDate: "2026-08-01",
      tags: ["Workshop", "Svelte", "JavaScript"],
      isBookmarked: false,
      applyLink: "https://svelte.dev/community",
      participants: 300,
      type: "workshop",
    },
    {
      id: 89,
      title: "Vue.js Student Conference 2026",
      description: "Progressive JavaScript framework conference for students.",
      organizer: "Vue.js Team",
      location: "Amsterdam, Netherlands",
      deadline: "2026-04-30",
      eventDate: "2026-06-20",
      tags: ["Conference", "Vue.js", "JavaScript"],
      isBookmarked: false,
      applyLink: "https://vuejs.org/community",
      participants: 500,
      type: "seminar",
    },
    {
      id: 90,
      title: "Angular Student Workshop Series",
      description: "Google's Angular framework workshop series.",
      organizer: "Google",
      location: "Multiple Cities",
      deadline: "2026-03-15",
      eventDate: "2026-05-01",
      tags: ["Workshop", "Angular", "TypeScript"],
      isBookmarked: false,
      applyLink: "https://angular.io/community",
      participants: 800,
      type: "workshop",
    },

    // Additional Indian Tech Events - 91-110
    {
      id: 91,
      title: "Cognizance 2026 - IIT Roorkee",
      description:
        "Technical festival focusing on innovation, research, and emerging technologies.",
      organizer: "IIT Roorkee",
      location: "Roorkee, Uttarakhand",
      deadline: "2026-02-01",
      eventDate: "2026-03-15",
      tags: ["Tech Festival", "Research", "Innovation", "Technology"],
      isBookmarked: false,
      applyLink: "https://cognizance.org.in",
      participants: 35000,
      type: "competition",
    },
    {
      id: 92,
      title: "Kshitij 2026 - IIT Kharagpur",
      description:
        "Technology festival featuring robotics competitions and technical workshops.",
      organizer: "IIT Kharagpur",
      location: "Kharagpur, West Bengal",
      deadline: "2025-12-25",
      eventDate: "2026-01-30",
      tags: ["Tech Festival", "Robotics", "Workshop", "Competition"],
      isBookmarked: true,
      applyLink: "https://kshitij.org",
      participants: 45000,
      type: "competition",
    },
    {
      id: 93,
      title: "Springfest 2026 - IIT Kharagpur",
      description:
        "Eastern India's largest social and cultural festival with celebrity performances.",
      organizer: "IIT Kharagpur",
      location: "Kharagpur, West Bengal",
      deadline: "2025-12-15",
      eventDate: "2026-01-25",
      tags: ["Cultural Festival", "Social", "Celebrity", "Music"],
      isBookmarked: false,
      applyLink: "https://springfest.iitkgp.ac.in",
      participants: 100000,
      type: "seminar",
    },
    {
      id: 94,
      title: "Oasis 2025 - BITS Pilani",
      description:
        "BITS Pilani's annual cultural festival in the heart of Rajasthan's desert.",
      organizer: "BITS Pilani",
      location: "Pilani, Rajasthan",
      deadline: "2025-10-01",
      eventDate: "2025-10-25",
      tags: ["Cultural Festival", "Desert", "Music", "Arts"],
      isBookmarked: false,
      applyLink: "https://bits-oasis.org",
      participants: 70000,
      type: "seminar",
    },
    {
      id: 95,
      title: "APOGEE 2026 - BITS Pilani",
      description:
        "Technical festival of BITS Pilani featuring innovation and entrepreneurship.",
      organizer: "BITS Pilani",
      location: "Pilani, Rajasthan",
      deadline: "2026-02-15",
      eventDate: "2026-03-20",
      tags: ["Tech Festival", "Innovation", "Entrepreneurship", "Competition"],
      isBookmarked: true,
      applyLink: "https://bits-apogee.org",
      participants: 50000,
      type: "competition",
    },

    // International Events - 96-110
    {
      id: 96,
      title: "Hack Cambridge 2026",
      description: "University of Cambridge's premier hackathon in the UK.",
      organizer: "University of Cambridge",
      location: "Cambridge, UK",
      deadline: "2026-01-15",
      eventDate: "2026-02-20",
      tags: ["Hackathon", "UK", "Innovation"],
      isBookmarked: false,
      applyLink: "https://hackcambridge.com",
      participants: 400,
      type: "hackathon",
    },
    {
      id: 97,
      title: "HackTUM 2026 - Technical University Munich",
      description: "Germany's largest student hackathon with European focus.",
      organizer: "TU Munich",
      location: "Munich, Germany",
      deadline: "2026-10-01",
      eventDate: "2026-11-15",
      tags: ["Hackathon", "Germany", "Europe"],
      isBookmarked: false,
      applyLink: "https://hacktum.de",
      participants: 800,
      type: "hackathon",
    },
    {
      id: 98,
      title: "Hack Oxford 2026",
      description:
        "Oxford University's student hackathon promoting innovation.",
      organizer: "University of Oxford",
      location: "Oxford, UK",
      deadline: "2026-02-28",
      eventDate: "2026-03-21",
      tags: ["Hackathon", "Oxford", "Innovation"],
      isBookmarked: false,
      applyLink: "https://hackoxford.com",
      participants: 300,
      type: "hackathon",
    },
    {
      id: 99,
      title: "HackMIT Europe 2026",
      description:
        "MIT's European hackathon bringing Boston innovation to Europe.",
      organizer: "MIT",
      location: "London, UK",
      deadline: "2026-06-15",
      eventDate: "2026-07-25",
      tags: ["Hackathon", "MIT", "Europe"],
      isBookmarked: false,
      applyLink: "https://hackmit.org/europe",
      participants: 600,
      type: "hackathon",
    },
    {
      id: 100,
      title: "Nordic.js Student Track 2026",
      description: "JavaScript conference in Stockholm with student program.",
      organizer: "Nordic.js",
      location: "Stockholm, Sweden",
      deadline: "2026-08-01",
      eventDate: "2026-09-10",
      tags: ["Conference", "JavaScript", "Nordic"],
      isBookmarked: false,
      applyLink: "https://nordicjs.com",
      participants: 400,
      type: "seminar",
    },

    // Sustainability and Social Impact - 101-115
    {
      id: 101,
      title: "Climate Change AI Student Workshop 2026",
      description:
        "Applying AI and machine learning to climate change challenges.",
      organizer: "Climate Change AI",
      location: "Online",
      deadline: "2026-04-15",
      eventDate: "2026-06-01",
      tags: ["Workshop", "Climate", "AI"],
      isBookmarked: false,
      applyLink: "https://climatechange.ai",
      participants: 500,
      type: "workshop",
    },
    {
      id: 102,
      title: "Sustainable Tech Student Summit 2026",
      description: "Technology solutions for environmental sustainability.",
      organizer: "Green Software Foundation",
      location: "San Francisco, CA",
      deadline: "2026-05-01",
      eventDate: "2026-07-15",
      tags: ["Conference", "Sustainability", "Green Tech"],
      isBookmarked: false,
      applyLink: "https://greensoftware.foundation",
      participants: 300,
      type: "seminar",
    },
    {
      id: 103,
      title: "Code for Good Student Hackathon 2026",
      description:
        "Hackathon focused on social impact and community solutions.",
      organizer: "Code for America",
      location: "Multiple Cities",
      deadline: "2026-03-15",
      eventDate: "2026-05-01",
      tags: ["Hackathon", "Social Impact", "Community"],
      isBookmarked: false,
      applyLink: "https://codeforamerica.org",
      participants: 1000,
      type: "hackathon",
    },
    {
      id: 104,
      title: "UN Global Goals Student Challenge 2026",
      description: "Technology solutions for UN Sustainable Development Goals.",
      organizer: "United Nations",
      location: "New York, NY",
      deadline: "2026-06-15",
      eventDate: "2026-09-01",
      tags: ["Competition", "UN Goals", "Sustainability"],
      isBookmarked: true,
      applyLink: "https://sdgs.un.org",
      participants: 2000,
      type: "competition",
    },
    {
      id: 105,
      title: "Ocean Protocol Data Economy Workshop",
      description:
        "Decentralized data sharing and ocean conservation technology.",
      organizer: "Ocean Protocol",
      location: "Online",
      deadline: "2026-07-01",
      eventDate: "2026-08-15",
      tags: ["Workshop", "Ocean", "Data"],
      isBookmarked: false,
      applyLink: "https://oceanprotocol.com",
      participants: 200,
      type: "workshop",
    },

    // Robotics and Hardware - 106-120
    {
      id: 106,
      title: "FIRST Robotics Student Championship 2026",
      description: "International robotics competition for students.",
      organizer: "FIRST",
      location: "Houston, TX",
      deadline: "2026-02-15",
      eventDate: "2026-04-20",
      tags: ["Competition", "Robotics", "Engineering"],
      isBookmarked: false,
      applyLink: "https://firstinspires.org",
      participants: 3000,
      type: "competition",
    },
    {
      id: 107,
      title: "Arduino Student Innovation Challenge",
      description: "Hardware prototyping competition with Arduino platforms.",
      organizer: "Arduino",
      location: "Turin, Italy",
      deadline: "2026-05-15",
      eventDate: "2026-07-01",
      tags: ["Competition", "Arduino", "Hardware"],
      isBookmarked: false,
      applyLink: "https://arduino.cc/education",
      participants: 800,
      type: "competition",
    },
    {
      id: 108,
      title: "Raspberry Pi Student Maker Faire 2026",
      description: "Maker movement celebration with Raspberry Pi projects.",
      organizer: "Raspberry Pi Foundation",
      location: "Cambridge, UK",
      deadline: "2026-06-01",
      eventDate: "2026-08-10",
      tags: ["Workshop", "Raspberry Pi", "Maker"],
      isBookmarked: false,
      applyLink: "https://raspberrypi.org/education",
      participants: 600,
      type: "workshop",
    },
    {
      id: 109,
      title: "Boston Dynamics Student Robotics Workshop",
      description: "Advanced robotics and mobility systems workshop.",
      organizer: "Boston Dynamics",
      location: "Waltham, MA",
      deadline: "2026-04-01",
      eventDate: "2026-06-15",
      tags: ["Workshop", "Robotics", "AI"],
      isBookmarked: false,
      applyLink: "https://bostondynamics.com/education",
      participants: 100,
      type: "workshop",
    },
    {
      id: 110,
      title: "Intel Student Hardware Innovation Contest",
      description: "Hardware design competition with Intel processors.",
      organizer: "Intel",
      location: "Santa Clara, CA",
      deadline: "2026-08-15",
      eventDate: "2026-10-01",
      tags: ["Competition", "Hardware", "Intel"],
      isBookmarked: false,
      applyLink: "https://intel.com/students",
      participants: 500,
      type: "competition",
    },

    // Blockchain and Web3 - 111-125
    {
      id: 111,
      title: "Ethereum Student Developer Bootcamp 2026",
      description: "Blockchain development workshop with Ethereum ecosystem.",
      organizer: "Ethereum Foundation",
      location: "Online",
      deadline: "2026-03-01",
      eventDate: "2026-05-15",
      tags: ["Workshop", "Blockchain", "Ethereum"],
      isBookmarked: false,
      applyLink: "https://ethereum.org/developers",
      participants: 1000,
      type: "workshop",
    },
    {
      id: 112,
      title: "Solana Student Hackathon 2026",
      description: "High-performance blockchain hackathon with Solana.",
      organizer: "Solana Labs",
      location: "San Francisco, CA",
      deadline: "2026-04-15",
      eventDate: "2026-06-01",
      tags: ["Hackathon", "Solana", "Web3"],
      isBookmarked: false,
      applyLink: "https://solana.com/developers",
      participants: 800,
      type: "hackathon",
    },
    {
      id: 113,
      title: "Polygon Student DeFi Workshop",
      description: "Decentralized finance development on Polygon network.",
      organizer: "Polygon",
      location: "Online",
      deadline: "2026-05-01",
      eventDate: "2026-07-01",
      tags: ["Workshop", "DeFi", "Polygon"],
      isBookmarked: false,
      applyLink: "https://polygon.technology/developers",
      participants: 400,
      type: "workshop",
    },
    {
      id: 114,
      title: "Chainlink Student Oracle Challenge",
      description: "Building decentralized oracle solutions with Chainlink.",
      organizer: "Chainlink Labs",
      location: "Online",
      deadline: "2026-06-15",
      eventDate: "2026-08-01",
      tags: ["Competition", "Oracle", "Chainlink"],
      isBookmarked: false,
      applyLink: "https://chain.link/developers",
      participants: 300,
      type: "competition",
    },
    {
      id: 115,
      title: "IPFS Student Storage Workshop 2026",
      description:
        "Decentralized storage solutions with InterPlanetary File System.",
      organizer: "Protocol Labs",
      location: "San Francisco, CA",
      deadline: "2026-07-01",
      eventDate: "2026-09-15",
      tags: ["Workshop", "IPFS", "Storage"],
      isBookmarked: false,
      applyLink: "https://ipfs.io/developers",
      participants: 200,
      type: "workshop",
    },

    // Career Development and Soft Skills - 116-130
    {
      id: 116,
      title: "LinkedIn Student Career Workshop 2026",
      description:
        "Professional networking and career development for students.",
      organizer: "LinkedIn",
      location: "Sunnyvale, CA",
      deadline: "2026-02-15",
      eventDate: "2026-04-10",
      tags: ["Workshop", "Career", "Networking"],
      isBookmarked: false,
      applyLink: "https://linkedin.com/students",
      participants: 500,
      type: "workshop",
    },
    {
      id: 117,
      title: "Toastmasters Student Leadership Conference",
      description: "Public speaking and leadership skills development.",
      organizer: "Toastmasters International",
      location: "Multiple Cities",
      deadline: "2026-05-01",
      eventDate: "2026-07-15",
      tags: ["Conference", "Leadership", "Speaking"],
      isBookmarked: false,
      applyLink: "https://toastmasters.org/students",
      participants: 1000,
      type: "seminar",
    },
    {
      id: 118,
      title: "McKinsey Student Case Competition 2026",
      description: "Business strategy and consulting case study competition.",
      organizer: "McKinsey & Company",
      location: "New York, NY",
      deadline: "2026-03-15",
      eventDate: "2026-05-20",
      tags: ["Competition", "Consulting", "Business"],
      isBookmarked: false,
      applyLink: "https://mckinsey.com/students",
      participants: 200,
      type: "competition",
    },
    {
      id: 119,
      title: "Goldman Sachs Student Trading Challenge",
      description: "Financial markets and trading simulation competition.",
      organizer: "Goldman Sachs",
      location: "New York, NY",
      deadline: "2026-04-01",
      eventDate: "2026-06-15",
      tags: ["Competition", "Finance", "Trading"],
      isBookmarked: false,
      applyLink: "https://goldmansachs.com/careers",
      participants: 300,
      type: "competition",
    },
    {
      id: 120,
      title: "TED Student Speaker Program 2026",
      description: "Student speaker development program with TED talks.",
      organizer: "TED",
      location: "Multiple Cities",
      deadline: "2026-06-01",
      eventDate: "2026-09-01",
      tags: ["Workshop", "Speaking", "TED"],
      isBookmarked: true,
      applyLink: "https://ted.com/participate/organize-a-local-tedx-event",
      participants: 100,
      type: "workshop",
    },

    // Research and Academia - 121-135
    {
      id: 121,
      title: "ACM Student Research Competition 2026",
      description:
        "Computer science research competition for undergraduate and graduate students.",
      organizer: "ACM",
      location: "Multiple Conferences",
      deadline: "2026-01-31",
      eventDate: "2026-06-01",
      tags: ["Competition", "Research", "Computer Science"],
      isBookmarked: false,
      applyLink: "https://acm.org/src",
      participants: 500,
      type: "competition",
    },
    {
      id: 122,
      title: "IEEE Student Paper Contest 2026",
      description: "Engineering and technology research paper competition.",
      organizer: "IEEE",
      location: "Global",
      deadline: "2026-03-15",
      eventDate: "2026-07-20",
      tags: ["Competition", "Research", "IEEE"],
      isBookmarked: false,
      applyLink: "https://ieee.org/students",
      participants: 1000,
      type: "competition",
    },
    {
      id: 123,
      title: "Nature Student Research Symposium 2026",
      description: "Scientific research presentation and networking event.",
      organizer: "Nature Publishing Group",
      location: "London, UK",
      deadline: "2026-05-15",
      eventDate: "2026-08-25",
      tags: ["Conference", "Research", "Science"],
      isBookmarked: false,
      applyLink: "https://nature.com/students",
      participants: 300,
      type: "seminar",
    },
    {
      id: 124,
      title: "NSF Student Research Conference 2026",
      description: "National Science Foundation student research showcase.",
      organizer: "National Science Foundation",
      location: "Washington, DC",
      deadline: "2026-04-01",
      eventDate: "2026-07-10",
      tags: ["Conference", "NSF", "Research"],
      isBookmarked: false,
      applyLink: "https://nsf.gov/students",
      participants: 400,
      type: "seminar",
    },
    {
      id: 125,
      title: "Simons Student Math Conference 2026",
      description: "Mathematics research and collaboration conference.",
      organizer: "Simons Foundation",
      location: "New York, NY",
      deadline: "2026-02-28",
      eventDate: "2026-05-15",
      tags: ["Conference", "Mathematics", "Research"],
      isBookmarked: false,
      applyLink: "https://simonsfoundation.org",
      participants: 200,
      type: "seminar",
    },

    // Entrepreneurship and Innovation - 126-140
    {
      id: 126,
      title: "Techstars Student Startup Weekend 2026",
      description: "54-hour startup creation event with mentor support.",
      organizer: "Techstars",
      location: "Multiple Cities",
      deadline: "2026-03-01",
      eventDate: "2026-04-15",
      tags: ["Workshop", "Startup", "Entrepreneurship"],
      isBookmarked: false,
      applyLink: "https://techstars.com/startup-weekend",
      participants: 2000,
      type: "workshop",
    },
    {
      id: 127,
      title: "500 Startups Student Demo Day 2026",
      description: "Student startup pitch competition and investor showcase.",
      organizer: "500 Startups",
      location: "San Francisco, CA",
      deadline: "2026-05-01",
      eventDate: "2026-08-15",
      tags: ["Competition", "Startup", "Pitch"],
      isBookmarked: false,
      applyLink: "https://500.co/students",
      participants: 100,
      type: "competition",
    },
    {
      id: 128,
      title: "SOCAP Student Social Entrepreneurship Summit",
      description: "Social impact and sustainable business conference.",
      organizer: "SOCAP",
      location: "San Francisco, CA",
      deadline: "2026-08-01",
      eventDate: "2026-10-15",
      tags: ["Conference", "Social Impact", "Entrepreneurship"],
      isBookmarked: false,
      applyLink: "https://socialcapitalmarkets.net",
      participants: 300,
      type: "seminar",
    },
    {
      id: 129,
      title: "Venture for America Student Fellowship 2026",
      description: "Entrepreneurship fellowship program in emerging cities.",
      organizer: "Venture for America",
      location: "Multiple Cities",
      deadline: "2026-01-15",
      eventDate: "2026-06-01",
      tags: ["Fellowship", "Entrepreneurship", "Career"],
      isBookmarked: false,
      applyLink: "https://ventureforamerica.org",
      participants: 200,
      type: "workshop",
    },
    {
      id: 130,
      title: "Babson Student Entrepreneurship Conference",
      description: "Leading entrepreneurship education and startup showcase.",
      organizer: "Babson College",
      location: "Wellesley, MA",
      deadline: "2026-02-15",
      eventDate: "2026-04-20",
      tags: ["Conference", "Entrepreneurship", "Education"],
      isBookmarked: false,
      applyLink: "https://babson.edu/students",
      participants: 500,
      type: "seminar",
    },

    // Additional Tech Events - 131-150
    {
      id: 131,
      title: "Stack Overflow Student Developer Survey 2026",
      description:
        "Annual developer insights and community research participation.",
      organizer: "Stack Overflow",
      location: "Online",
      deadline: "2026-01-31",
      eventDate: "2026-03-15",
      tags: ["Survey", "Developer", "Community"],
      isBookmarked: false,
      applyLink: "https://stackoverflow.com/dev-survey",
      participants: 50000,
      type: "workshop",
    },
    {
      id: 132,
      title: "GitLab Student DevSecOps Workshop 2026",
      description: "DevSecOps practices and security in software development.",
      organizer: "GitLab",
      location: "San Francisco, CA",
      deadline: "2026-04-15",
      eventDate: "2026-06-10",
      tags: ["Workshop", "DevSecOps", "Security"],
      isBookmarked: false,
      applyLink: "https://gitlab.com/students",
      participants: 300,
      type: "workshop",
    },
    {
      id: 133,
      title: "Atlassian Team Student Summit 2026",
      description:
        "Learn about collaboration tools and agile development practices.",
      organizer: "Atlassian",
      location: "Las Vegas, NV",
      deadline: "2026-03-01",
      eventDate: "2026-04-29",
      tags: ["Conference", "Collaboration", "Agile"],
      isBookmarked: false,
      applyLink: "https://atlassian.com/team",
      participants: 800,
      type: "seminar",
    },
    {
      id: 134,
      title: "Zoom Developer Student Platform 2026",
      description: "Video communications platform development conference.",
      organizer: "Zoom",
      location: "San Jose, CA",
      deadline: "2026-07-15",
      eventDate: "2026-08-20",
      tags: ["Conference", "Video Tech", "API"],
      isBookmarked: false,
      applyLink: "https://zoom.us/events",
      participants: 800,
      type: "seminar",
    },
    {
      id: 135,
      title: "Slack Student App Development Workshop",
      description: "Building workplace collaboration apps and integrations.",
      organizer: "Slack",
      location: "San Francisco, CA",
      deadline: "2026-05-15",
      eventDate: "2026-07-01",
      tags: ["Workshop", "Slack", "Integration"],
      isBookmarked: false,
      applyLink: "https://api.slack.com/students",
      participants: 200,
      type: "workshop",
    },
    {
      id: 136,
      title: "Dropbox Student API Challenge 2026",
      description:
        "Cloud storage and file sharing API development competition.",
      organizer: "Dropbox",
      location: "San Francisco, CA",
      deadline: "2026-06-01",
      eventDate: "2026-08-15",
      tags: ["Competition", "API", "Cloud Storage"],
      isBookmarked: false,
      applyLink: "https://dropbox.com/developers",
      participants: 300,
      type: "competition",
    },
    {
      id: 137,
      title: "Box Student Content Management Workshop",
      description: "Enterprise content management and collaboration solutions.",
      organizer: "Box",
      location: "Redwood City, CA",
      deadline: "2026-04-30",
      eventDate: "2026-06-20",
      tags: ["Workshop", "Content Management", "Enterprise"],
      isBookmarked: false,
      applyLink: "https://box.com/developers",
      participants: 150,
      type: "workshop",
    },
    {
      id: 138,
      title: "Adobe Student Creative Challenge 2026",
      description: "Digital creativity and design tool competition.",
      organizer: "Adobe",
      location: "San Jose, CA",
      deadline: "2026-07-01",
      eventDate: "2026-09-01",
      tags: ["Competition", "Creative", "Design"],
      isBookmarked: false,
      applyLink: "https://adobe.com/students",
      participants: 1000,
      type: "competition",
    },
    {
      id: 139,
      title: "Autodesk Student Design Competition 2026",
      description: "CAD and 3D design software competition for students.",
      organizer: "Autodesk",
      location: "San Rafael, CA",
      deadline: "2026-05-15",
      eventDate: "2026-08-01",
      tags: ["Competition", "CAD", "3D Design"],
      isBookmarked: false,
      applyLink: "https://autodesk.com/education",
      participants: 500,
      type: "competition",
    },
    {
      id: 140,
      title: "Epic Systems Engineering Program 2026",
      description:
        "Healthcare software engineering internship and career opportunities.",
      organizer: "Epic Systems",
      location: "Madison, WI",
      deadline: "2026-01-31",
      eventDate: "2026-06-01",
      tags: ["Internship", "Healthcare", "Software Engineering"],
      isBookmarked: true,
      applyLink: "https://epic.com/careers",
      participants: 400,
      type: "internship",
    },
    {
      id: 141,
      title: "Indeed Engineering Career Fair Fall 2025",
      description:
        "Career fair and technical interviews for software engineering roles.",
      organizer: "Indeed",
      location: "Austin, TX",
      deadline: "2025-09-01",
      eventDate: "2025-10-15",
      tags: ["Career Fair", "Software Engineering", "Job Search"],
      isBookmarked: false,
      applyLink: "https://indeed.com/careers",
      participants: 500,
      type: "seminar",
    },
    {
      id: 142,
      title: "Quora ML/AI Internship 2026",
      description:
        "Machine learning engineering internship working on knowledge platforms.",
      organizer: "Quora",
      location: "Mountain View, CA",
      deadline: "2026-02-01",
      eventDate: "2026-06-01",
      tags: ["Internship", "Machine Learning", "AI"],
      isBookmarked: false,
      applyLink: "https://quora.com/careers",
      participants: 50,
      type: "internship",
    },
    {
      id: 143,
      title: "Webflow No-Code Summit 2026",
      description: "Learn visual development and no-code design principles.",
      organizer: "Webflow",
      location: "San Francisco, CA",
      deadline: "2026-08-01",
      eventDate: "2026-09-15",
      tags: ["Conference", "No-Code", "Design"],
      isBookmarked: false,
      applyLink: "https://webflow.com/events",
      participants: 1000,
      type: "seminar",
    },
    {
      id: 144,
      title: "Cloudflare Workers Student Program 2026",
      description:
        "Serverless computing workshop and internship opportunities.",
      organizer: "Cloudflare",
      location: "San Francisco, CA",
      deadline: "2026-05-01",
      eventDate: "2026-06-15",
      tags: ["Workshop", "Serverless", "Cloud Computing"],
      isBookmarked: false,
      applyLink: "https://cloudflare.com/careers",
      participants: 300,
      type: "workshop",
    },
    {
      id: 145,
      title: "Heroku Student Platform Workshop 2026",
      description:
        "Cloud application deployment and platform-as-a-service workshop.",
      organizer: "Heroku",
      location: "San Francisco, CA",
      deadline: "2026-04-01",
      eventDate: "2026-05-20",
      tags: ["Workshop", "PaaS", "Deployment"],
      isBookmarked: false,
      applyLink: "https://heroku.com/students",
      participants: 200,
      type: "workshop",
    },
    {
      id: 146,
      title: "DigitalOcean Student Hackathon 2026",
      description: "Cloud infrastructure hackathon with DigitalOcean credits.",
      organizer: "DigitalOcean",
      location: "New York, NY",
      deadline: "2026-06-15",
      eventDate: "2026-08-01",
      tags: ["Hackathon", "Cloud", "Infrastructure"],
      isBookmarked: false,
      applyLink: "https://digitalocean.com/students",
      participants: 400,
      type: "hackathon",
    },
    {
      id: 147,
      title: "Linode Student Cloud Computing Workshop",
      description: "Linux cloud computing and server management workshop.",
      organizer: "Linode",
      location: "Philadelphia, PA",
      deadline: "2026-05-15",
      eventDate: "2026-07-10",
      tags: ["Workshop", "Linux", "Cloud"],
      isBookmarked: false,
      applyLink: "https://linode.com/students",
      participants: 250,
      type: "workshop",
    },
    {
      id: 148,
      title: "MongoDB Atlas Student Developer Day",
      description: "NoSQL database development and cloud atlas workshop.",
      organizer: "MongoDB",
      location: "New York, NY",
      deadline: "2026-03-15",
      eventDate: "2026-05-01",
      tags: ["Workshop", "Database", "NoSQL"],
      isBookmarked: false,
      applyLink: "https://mongodb.com/students",
      participants: 300,
      type: "workshop",
    },
    {
      id: 149,
      title: "Redis Student Data Structures Workshop",
      description: "In-memory data structure store and caching workshop.",
      organizer: "Redis Labs",
      location: "San Francisco, CA",
      deadline: "2026-04-15",
      eventDate: "2026-06-01",
      tags: ["Workshop", "Redis", "Caching"],
      isBookmarked: false,
      applyLink: "https://redis.com/students",
      participants: 200,
      type: "workshop",
    },
    {
      id: 150,
      title: "Elasticsearch Student Search Workshop 2026",
      description: "Search and analytics engine workshop for students.",
      organizer: "Elastic",
      location: "Amsterdam, Netherlands",
      deadline: "2026-06-01",
      eventDate: "2026-08-15",
      tags: ["Workshop", "Search", "Analytics"],
      isBookmarked: false,
      applyLink: "https://elastic.co/students",
      participants: 250,
      type: "workshop",
    },
  ]
};
